apiVersion: v1
kind: ConfigMap
metadata:
    name: kfk-brkr-configmap
    namespace: ns-infra
data:
    KAFKA_BROKER_ID: "1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper.ns-infra.svc.cluster.local:2181"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kfk-brkr.ns-infra.svc.cluster.local:29092,PLAINTEXT_HOST://kfk-brkr.ns-infra.svc.cluster.local:9092"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"