apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: ns-infra
spec:
  selector:
    matchLabels:
      app: kafka-broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - image: confluentinc/cp-kafka:latest
          name: kafka-broker
          envFrom:
            - configMapRef:
                name: kafka-broker-configmap
          ports:
            - containerPort: 9092
              name: kafka-broker
            - containerPort: 29092
              name: kafka-plain
          volumeMounts:
            - name: kafka-broker-persistent-storage
              mountPath: /var/lib/kafka-broker
      volumes:
        - name: kafka-broker-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-broker-pv-claim