apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfk-brkr
  namespace: ns-infra
spec:
  selector:
    matchLabels:
      app: kfk-brkr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kfk-brkr
    spec:
      containers:
        - image: confluentinc/cp-kafka:latest
          name: kfk-brkr
          envFrom:
            - configMapRef:
                name: kfk-brkr-configmap
          ports:
            - containerPort: 9092
              name: kfk-brkr
            - containerPort: 29092
              name: kfk-plain
          volumeMounts:
            - name: kfk-brkr-persistent-storage
              mountPath: /var/lib/kafka-broker
      volumes:
        - name: kfk-brkr-persistent-storage
          persistentVolumeClaim:
            claimName: kfk-brkr-pv-claim