apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: ns-infra
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      name: mq-9092
    - port: 29092
      name: mq-29092
  selector:
    app: kafka-broker