apiVersion: v1
kind: ConfigMap
metadata:
    name: schma-regstry-configmap
    namespace: ns-infra
data:
    SCHEMA_REGISTRY_HOST_NAME: "schma-regstry"
    SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-broker:29092"
    SCHEMA_REGISTRY_DEBUG: "true"