apiVersion: apps/v1
kind: Deployment
metadata:
  name: schma-regstry
  namespace: ns-infra
spec:
  selector:
    matchLabels:
      app: schma-regstry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: schma-regstry
    spec:
      containers:
        - image: confluentinc/cp-schema-registry:latest
          name: schma-regstry
          envFrom:
            - configMapRef:
                name: schma-regstry-configmap
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: schma-regstry-persistent-storage
              mountPath: /var/lib/schema-registry
      volumes:
        - name: schma-regstry-persistent-storage
          persistentVolumeClaim:
            claimName: schma-regstry-pv-claim